In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print(PROJECT_ROOT)
print(RAW_DIR)

c:\Users\hyss2\Desktop\nhaven-higher-ed-analysis
c:\Users\hyss2\Desktop\nhaven-higher-ed-analysis\data\raw

Path.cwd()：获取当前notebook运行时的工作目录。Jupyter notebook的"当前目录"默认是notebook文件所在位置，也就是nhaven-higher-ed-analysis/notebooks/。

parent：往上退一级，回到项目根目录nhaven-higher-ed-analysis/。这样无论你以后从哪里启动Jupyter，只要notebook还在notebooks/文件夹里，这行代码都能正确定位到根目录——不依赖你电脑上的绝对路径（比如/Users/gigi/Desktop/...），这对以后要不要分享给别人看/上传GitHub都很重要。

RAW_DIR/PROCESSED_DIR：提前把两个文件夹路径定义成变量，而不是每次读写文件都手打路径字符串。好处是如果以后文件夹结构变了，只改这两行，不用满notebook找字符串改。

最后两个print是验证性代码，不是最终逻辑的一部分——运行完看看打印出来的路径对不对，确认没跑偏，之后可以留着也可以删掉。

In [3]:
raw_files = list(RAW_DIR.glob("*.csv"))
print(raw_files)

[WindowsPath('c:/Users/hyss2/Desktop/nhaven-higher-ed-analysis/data/raw/Data_7-3-2026.csv')]

RAW_DIR.glob("*.csv")：glob是"模式匹配"，*.csv表示"匹配所有以.csv结尾的文件"。这样写而不是直接手打文件名，是因为文件名里带了日期（Data_7-3-2026.csv），以后你重新导出数据、文件名一变，硬编码的文件名就得手动改。用glob扫描文件夹，代码更"活"，不依赖具体文件名。

list(...)：glob返回的是一个生成器（generator），不是直接能看到内容的东西，包一层list()才能打印出实际的文件路径列表。

In [4]:
raw_path = raw_files[0]
df = pd.read_csv(raw_path)

print(df.shape)
df.head()

(4, 39)

,UnitID,Institution Name,4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_23_RV),6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_23_RV),Part time total (EF2023_RV All students Undergraduate total),Full time total (EF2023_RV All students Undergraduate total),4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_21_RV),6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_21_RV),Part time total (EF2021_RV All students Undergraduate total),Full time total (EF2021_RV All students Undergraduate total),...,Part-time retention rate 2021 (EF2021D_RV),Full-time retention rate 2019 (EF2019D_RV),Part-time retention rate 2019 (EF2019D_RV),Full-time retention rate 2017 (EF2017D_RV),Part-time retention rate 2017 (EF2017D_RV),Full-time retention rate 2015 (EF2015D_RV),Part-time retention rate 2015 (EF2015D_RV),Full-time retention rate 2013 (EF2013D_RV),Part-time retention rate 2013 (EF2013D_RV),Unnamed: 38
0,130226,Quinnipiac University,77,80,178,6070,65,69,313,5985,...,NaN,84,0.0,86,17.0,87,100.0,85,100.0,NaN
1,130493,Southern Connecticut State University,29,52,1389,5392,29,52,1156,5644,...,23.0,73,33.0,78,23.0,75,18.0,75,50.0,NaN
2,129941,University of New Haven,52,66,317,4548,51,61,305,4718,...,0.0,77,33.0,79,40.0,79,80.0,76,75.0,NaN
3,130794,Yale University,88,97,13,6805,88,97,4,6532,...,NaN,99,NaN,99,NaN,99,NaN,99,NaN,NaN

raw_files[0]：上一步raw_files是个列表（哪怕只有一个文件，glob返回的也是列表）。因为你现在data/raw/里只有这一个CSV，所以直接取第0个元素就是它。注意：以后如果你往raw/文件夹里放了不止一个CSV（比如又下载了新版本忘记删旧的），这行代码会出问题——它永远只读列表里第一个，可能不是你想要的那个。现阶段先这样写没问题，但养成习惯：以后raw/文件夹里只放"当前正在用"的那一份数据，或者以后我们可以改成更精确地指定文件名。

pd.read_csv(raw_path)：pandas读取CSV的标准函数，返回一个DataFrame对象（你可以理解成Python里的Excel表格）。Path对象可以直接传给read_csv，不需要转成字符串，pandas自己认得。

df.shape：打印(行数, 列数)。你之前我帮你看过这份数据，应该是(4, 39)——4所学校，39列（包括那个全空的"Unnamed: 38"）。这一步是用来验证读取有没有出问题——如果行数列数跟预期差很远（比如变成1行或者上百列），说明CSV的分隔符、编码、表头行数不对，需要调整read_csv的参数。

df.head()：显示前5行数据（这里数据总共才4行，所以会全部显示）。这是目视检查——看看列名有没有乱码、数字有没有被读成奇怪的格式、有没有整行整列错位。notebook里df.head()作为cell最后一行，会自动渲染成好看的表格，不需要额外套print()。

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 39 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   UnitID                                                                               4 non-null      int64
 1   Institution Name                                                                     4 non-null      str
 2   4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_23_RV)  4 non-null      int64
 3   6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_23_RV)  4 non-null      int64
 4   Part time total (EF2023_RV  All students  Undergraduate total)                       4 non-null      int64
 5   Full time total (EF2023_RV  All students  Undergraduate total)                       4 non-null      int64
 6   4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_21_RV)  4 non-null      int64
 7   6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_21_RV)  4 non-null      int64
 8   Part time total (EF2021_RV  All students  Undergraduate total)                       4 non-null      int64
 9   Full time total (EF2021_RV  All students  Undergraduate total)                       4 non-null      int64
 10  4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_19_RV)  4 non-null      int64
 11  6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_19_RV)  4 non-null      int64
 12  Part time total (EF2019_RV  All students  Undergraduate total)                       4 non-null      int64
 13  Full time total (EF2019_RV  All students  Undergraduate total)                       4 non-null      int64
 14  4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_17_RV)  4 non-null      int64
 15  6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_17_RV)  4 non-null      int64
 16  Part time total (EF2017_RV  All students  Undergraduate total)                       4 non-null      int64
 17  Full time total (EF2017_RV  All students  Undergraduate total)                       4 non-null      int64
 18  4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_15_RV)  4 non-null      int64
 19  6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_15_RV)  4 non-null      int64
 20  Part time total (EF2015_RV  All students  Undergraduate total)                       4 non-null      int64
 21  Full time total (EF2015_RV  All students  Undergraduate total)                       4 non-null      int64
 22  4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_13_RV)  4 non-null      int64
 23  6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_13_RV)  4 non-null      int64
 24  Part time total (EF2013_RV  All students  Undergraduate total)                       4 non-null      int64
 25  Full time total (EF2013_RV  All students  Undergraduate total)                       4 non-null      int64
 26  Full-time retention rate  2023 (EF2023D_RV)                                          4 non-null      int64
 27  Part-time retention rate  2023 (EF2023D_RV)                                          3 non-null      float64
 28  Full-time retention rate  2021 (EF2021D_RV)                                          4 non-null      int64
 29  Part-time retention rate  2021 (EF2021D_RV)                                          2 non-null      float64
 30  Full-time retention rate  2019 (EF2019D_RV)                                          4 non-null      int64
 31  Part-time retention rate  2019 (EF2019D_RV)                                          3 non-null      float64
 32  Full-time retention rate  2017 (EF2017D_RV)                                          4 non-null      int64
 33  Part-time retention rate  2017 (EF2017D_RV)                                          3 non-null      float64
 34  Full-time retention rate  2015 (EF2015D_RV)                                          4 non-null      int64
 35  Part-time retention rate  2015 (EF2015D_RV)                                          3 non-null      float64
 36  Full-time retention rate  2013 (EF2013D_RV)                                          4 non-null      int64
 37  Part-time retention rate  2013 (EF2013D_RV)                                          3 non-null      float64
 38  Unnamed: 38                                                                          0 non-null      float64
dtypes: float64(7), int64(31), str(1)
memory usage: 1.3 KB

In [6]:
df = df.drop(columns=["Unnamed: 38"])
df.shape

(4, 38)

In [7]:
for col in df.columns:
    print(col)

UnitID
Institution Name
4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_23_RV)
6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_23_RV)
Part time total (EF2023_RV  All students  Undergraduate total)
Full time total (EF2023_RV  All students  Undergraduate total)
4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_21_RV)
6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_21_RV)
Part time total (EF2021_RV  All students  Undergraduate total)
Full time total (EF2021_RV  All students  Undergraduate total)
4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_19_RV)
6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_19_RV)
Part time total (EF2019_RV  All students  Undergraduate total)
Full time total (EF2019_RV  All students  Undergraduate total)
4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_17_RV)
6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_17_RV)
Part time total (EF2017_RV  All students  Undergraduate total)
Full time total (EF2017_RV  All students  Undergraduate total)
4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_15_RV)
6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_15_RV)
Part time total (EF2015_RV  All students  Undergraduate total)
Full time total (EF2015_RV  All students  Undergraduate total)
4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_13_RV)
6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_13_RV)
Part time total (EF2013_RV  All students  Undergraduate total)
Full time total (EF2013_RV  All students  Undergraduate total)
Full-time retention rate  2023 (EF2023D_RV)
Part-time retention rate  2023 (EF2023D_RV)
Full-time retention rate  2021 (EF2021D_RV)
Part-time retention rate  2021 (EF2021D_RV)
Full-time retention rate  2019 (EF2019D_RV)
Part-time retention rate  2019 (EF2019D_RV)
Full-time retention rate  2017 (EF2017D_RV)
Part-time retention rate  2017 (EF2017D_RV)
Full-time retention rate  2015 (EF2015D_RV)
Part-time retention rate  2015 (EF2015D_RV)
Full-time retention rate  2013 (EF2013D_RV)
Part-time retention rate  2013 (EF2013D_RV)

In [8]:
rename_map = {
    "UnitID": "unit_id",
    "Institution Name": "institution",
}

years = [2023, 2021, 2019, 2017, 2015, 2013]

for year in years:
    rename_map[f"4-year Graduation rate - bachelor's degree within 100% of normal time (GR200_{str(year)[-2:]}_RV)"] = f"grad_rate_4yr_{year}"
    rename_map[f"6-year Graduation rate - bachelor's degree within 150% of normal time (GR200_{str(year)[-2:]}_RV)"] = f"grad_rate_6yr_{year}"
    rename_map[f"Part time total (EF{year}_RV  All students  Undergraduate total)"] = f"enroll_pt_{year}"
    rename_map[f"Full time total (EF{year}_RV  All students  Undergraduate total)"] = f"enroll_ft_{year}"
    rename_map[f"Full-time retention rate  {year} (EF{year}D_RV)"] = f"retention_ft_{year}"
    rename_map[f"Part-time retention rate  {year} (EF{year}D_RV)"] = f"retention_pt_{year}"

print(len(rename_map))

38

f"..."是Python的f-string语法，{year}会被替换成变量的实际值。比如year=2023时，f"grad_rate_4yr_{year}"就变成字符串"grad_rate_4yr_2023"。

str(year)[-2:]：把年份2023转成字符串"2023"，再取最后两位"23"——这是因为IPEDS原始列名里的编码是两位数（GR200_23_RV），不是完整四位年份。

In [9]:
missing = [col for col in rename_map.keys() if col not in df.columns]
print(missing)

[]

In [10]:
df = df.rename(columns=rename_map)
df.columns.tolist()

['unit_id',
 'institution',
 'grad_rate_4yr_2023',
 'grad_rate_6yr_2023',
 'enroll_pt_2023',
 'enroll_ft_2023',
 'grad_rate_4yr_2021',
 'grad_rate_6yr_2021',
 'enroll_pt_2021',
 'enroll_ft_2021',
 'grad_rate_4yr_2019',
 'grad_rate_6yr_2019',
 'enroll_pt_2019',
 'enroll_ft_2019',
 'grad_rate_4yr_2017',
 'grad_rate_6yr_2017',
 'enroll_pt_2017',
 'enroll_ft_2017',
 'grad_rate_4yr_2015',
 'grad_rate_6yr_2015',
 'enroll_pt_2015',
 'enroll_ft_2015',
 'grad_rate_4yr_2013',
 'grad_rate_6yr_2013',
 'enroll_pt_2013',
 'enroll_ft_2013',
 'retention_ft_2023',
 'retention_pt_2023',
 'retention_ft_2021',
 'retention_pt_2021',
 'retention_ft_2019',
 'retention_pt_2019',
 'retention_ft_2017',
 'retention_pt_2017',
 'retention_ft_2015',
 'retention_pt_2015',
 'retention_ft_2013',
 'retention_pt_2013']

In [11]:
long_df = pd.wide_to_long(
    df,
    stubnames=["grad_rate_4yr", "grad_rate_6yr", "enroll_pt", "enroll_ft", "retention_ft", "retention_pt"],
    i=["unit_id", "institution"],
    j="year",
    sep="_"
)

long_df = long_df.reset_index()
print(long_df.shape)
long_df.head(10)

(24, 9)

,unit_id,institution,year,grad_rate_4yr,grad_rate_6yr,enroll_pt,enroll_ft,retention_ft,retention_pt
0,130226,Quinnipiac University,2023,77,80,178,6070,87,0.0
1,130226,Quinnipiac University,2021,65,69,313,5985,87,NaN
2,130226,Quinnipiac University,2019,71,75,302,6543,84,0.0
3,130226,Quinnipiac University,2017,71,76,346,6959,86,17.0
4,130226,Quinnipiac University,2015,72,76,279,6703,87,100.0
5,130226,Quinnipiac University,2013,72,77,235,6307,85,100.0
6,130493,Southern Connecticut State University,2023,29,52,1389,5392,76,40.0
7,130493,Southern Connecticut State University,2021,29,52,1156,5644,72,23.0
8,130493,Southern Connecticut State University,2019,20,48,1161,6801,73,33.0
9,130493,Southern Connecticut State University,2017,23,52,1133,6814,78,23.0

stubnames：告诉函数"这6个是指标名的词根（stub），你要在列名里找这些前缀，后面跟着的下划线+数字就是要拆出来的年份"。顺序不影响结果，但我保持了和你数出来一致的6个。

i=["unit_id", "institution"]：这是"每一行的身份证"——转换后，这两列的组合用来标识"这是哪所学校"，不会被拆开，保留原样。

j="year"：新生成的、用来存放"年份"的列，取名叫year。
sep="_"：前面解释过，告诉函数指标名和年份之间的分隔符是下划线。

pd.wide_to_long()执行完，返回的结果默认把i和j指定的列变成索引（index），而不是普通列，这个是 wide_to_long比较反直觉的地方，新手很容易漏掉这一步，导致后面unit_id/year用不了。所以必须紧接着调用.reset_index()，把它们从索引"还原"成普通列，才能正常用df["year"]这样取值。

print(long_df.shape)：验证转换结果。我们预期应该是(24, 9)——4所学校×6年=24行，9列（unit_id, institution, year + 6个指标）。这是刚才你数出"6种指标"派上用场的地方,用来验证转换对不对。

In [12]:
long_df[long_df["institution"] == "Yale University"].sort_values("year")

,unit_id,institution,year,grad_rate_4yr,grad_rate_6yr,enroll_pt,enroll_ft,retention_ft,retention_pt
23,130794,Yale University,2013,89,97,6,5424,99,NaN
22,130794,Yale University,2015,90,98,23,5509,99,NaN
21,130794,Yale University,2017,88,97,3,5743,99,NaN
20,130794,Yale University,2019,86,97,4,6088,99,NaN
19,130794,Yale University,2021,88,97,4,6532,98,NaN
18,130794,Yale University,2023,88,97,13,6805,99,NaN

In [13]:
long_df.isnull().sum()

unit_id          0
institution      0
year             0
grad_rate_4yr    0
grad_rate_6yr    0
enroll_pt        0
enroll_ft        0
retention_ft     0
retention_pt     7
dtype: int64

In [14]:
long_df[long_df["retention_pt"].isnull()][["institution","year","enroll_pt","retention_pt"]]

              institution  year  enroll_pt  retention_pt
1   Quinnipiac University  2021        313           NaN
18        Yale University  2023         13           NaN
19        Yale University  2021          4           NaN
20        Yale University  2019          4           NaN
21        Yale University  2017          3           NaN
22        Yale University  2015         23           NaN
23        Yale University  2013          6           NaN

In [15]:
long_df.dtypes

unit_id            int64
institution          str
year               int64
grad_rate_4yr      int64
grad_rate_6yr      int64
enroll_pt          int64
enroll_ft          int64
retention_ft       int64
retention_pt     float64
dtype: object

In [16]:
output_path = PROCESSED_DIR / "nhaven_higher_ed_clean.csv"
long_df.to_csv(output_path, index=False)

print(f"Save to : {output_path}")

Save to : c:\Users\hyss2\Desktop\nhaven-higher-ed-analysis\data\processed\nhaven_higher_ed_clean.csv